config/routes.rb
Rails.application.routes.draw do

  resources :centres
  resources :messages

  root 'centres#index'

  get 'layouts/assistant' => 'layouts#assistant'

  get 'messages/index' => 'messages#index'

  get 'twilio/index' => 'twilio#index'

end

app/models/centre.rb
class Centre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/centres_controller.rb
class CentresController < ApplicationController
  def index
    @centres = Centre.all
  end

  def show
    @centre = Centre.find(params[:id])
  end

  def destroy
    @centre = Centre.find(params[:id])
    @centre.destroy

    redirect_to centres_path
  end

  def new
  end

  def edit
    @centre = Centre.find(params[:id])
  end

  def create
    @centre = Centre.new(centre_params)

    @centre.save
    redirect_to @centre
  end

  def update
    @centre = Centre.find(params[:id])

    if @centre.update(centre_params)
      redirect_to @centre
    else
      render 'edit'
    end
  end



  private
    def centre_params
      params.require(:centre).permit(:name, :location, :description, :status, :key_contacts, :assistant_contacts, :medical, :medical_level, :equiptment, :equiptment_level, :people, :people_level, :food, :food_level, :other)
    end

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def assistant

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @message.save
  end

end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  def index
    @message = params[:Body]
    @sender = params[:From]
    render 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/centres/edit.html.haml
%section.intro
  %h1 Edit this centre

%section
  .inner
    = form_for :centre, url: centre_path(@centre), method: :patch do |f|

      %fieldset
        = f.label :name
        = f.text_field :name

      %fieldset
        = f.label :location
        = f.text_field :location

      %fieldset
        = f.label :description
        = f.text_area :description

      %fieldset
        %label
          = f.radio_button :status, 'active'
          Active centre
        %label
          = f.radio_button :status, 'inactive'
          Inactive centre
        %br
        %br

      %fieldset
        = f.label :key_contacts
        = f.text_area :key_contacts


      %fieldset
        = f.label :assistant_contacts
        = f.text_area :assistant_contacts

      %fieldset
        = f.label :medical
        = f.text_area :medical
        %br
        = f.label :medical_level
        = f.text_field :medical_level

      %fieldset
        = f.label :equiptment, 'Equipment'
        = f.text_area :equiptment
        %br
        = f.label :equiptment_level
        = f.text_field :equiptment_level


      %fieldset
        = f.label :people
        = f.text_area :people
        %br
        = f.label :people_level
        = f.text_field :people_level

      %fieldset
        = f.label :food
        = f.text_area :food
        %br
        = f.label :food_level
        = f.text_field :food_level

      %fieldset
        = f.label :other
        = f.text_area :other

      %br
      / = link_to 'Destroy', centre_path(@centre),
      /         method: :delete,
      /         data: { confirm: 'Are you sure?' }
      = f.submit

app/views/centres/index.html.haml
%section.intro
  %h1 How can you help support emergency treatment centres?

%section.links

  %p Pairing volunteer assistants from around the world with emergency treatment centres, for up to date, open reporting on supplies and resources.
  %br
  %p Use this site to browse a centre's needs, get support for your treatment centre or volunteer to help.


%section#centres
  -@centres.each do |centre|
    =link_to(centre_path(centre), :class => 'centre') do
      .image
      %h3
        =centre.name
        -unless centre.location.blank?
          \- #{centre.location}

%section
  #find
    %h2 Get help
    %p To connect with an assistant simply text your name and a brief overview of your situation to:
    %h3 +44 7481 3394 57

  #help
    %h2 Volunteer to become an assistant
    %p Help promote the needs of emergency health and treatment centres by relaying information between text and this site.
    %br
    = link_to "Become an assistant", messages_path

app/views/centres/new.html.haml
%section.intro
  %h1 Set up a centre

%section
  .inner
    = form_for :centre, url: centres_path do |f|

      %fieldset
        = f.label :name
        = f.text_field :name

      %fieldset
        = f.label :location
        = f.text_field :location

      %fieldset
        = f.label :description
        = f.text_area :description

      %fieldset
        %label
          = f.radio_button :status, 'active'
          Active centre
        %label
          = f.radio_button :status, 'inactive'
          Inactive centre
        %br
        %br

      %fieldset
        = f.label :key_contacts
        = f.text_area :key_contacts


      %fieldset
        = f.label :assistant_contacts
        = f.text_area :assistant_contacts

      %fieldset
        = f.label :medical
        = f.text_area :medical
        %br
        = f.label :medical_level
        = f.text_field :medical_level

      %fieldset
        = f.label :equiptment, 'Equipment'
        = f.text_area :equiptment
        %br
        = f.label :equiptment_level
        = f.text_field :equiptment_level


      %fieldset
        = f.label :people
        = f.text_area :people
        %br
        = f.label :people_level
        = f.text_field :people_level

      %fieldset
        = f.label :food
        = f.text_area :food
        %br
        = f.label :food_level
        = f.text_field :food_level

      %fieldset
        = f.label :other
        = f.text_area :other

      %br

      = f.submit

app/views/centres/show.html.haml
#show
  %section.intro
    %h1
      #{@centre.name}
      -unless @centre.location.blank?
        \- #{@centre.location}

    %p=@centre.description
    %br
    %p
      %strong Status:
      =@centre.status.capitalize



  %section.contact-info
    %p
      %strong Centre contact:
      =@centre.key_contacts
    %p
      %strong Assistant contact:
      =@centre.assistant_contacts

  .left-align
    -unless @centre.medical.blank?
      %section
        .inner
          %h2 Medical supplies
          %i f
          %p=@centre.medical
          .level
            %br
            %br
            %p.urgency
              %strong Urgency:
              #{@centre.medical_level} out of 10
          .clear

    -unless @centre.equiptment.blank?
      %section
        .inner
          %h2 Equipment
          %i d
          %p=@centre.equiptment
          .level
            %br
            %br
            %p.urgency
              %strong Urgency:
              #{@centre.equiptment_level} out of 10
          .clear

    -unless @centre.people.blank?
      %section
        .inner
          %h2 People
          %i a
          %p
            =@centre.people
            %br
            %br
            %a{:href => 'http://www.vsointernational.org/fighting-poverty/where-we-work/sierra-leone', :target => 'blank'}
              Learn about becoming a volunteer
          .level
            %br
            %br
            %p.urgency
              %strong Urgency:
              #{@centre.people_level} out of 10
          .clear

    -unless @centre.food.blank?
      %section
        .inner
          %h2 Food and supplies
          %i e
          %p=@centre.food
          .level
            %br
            %br
            %p.urgency
              %strong Urgency:
              #{@centre.food_level} out of 10
          .clear

    -unless @centre.other.blank?
      %section
        .inner
          %h2 Other information
          %i d
          %p=@centre.other

app/views/layouts/_header.html.haml
%header
  =link_to('Emergency treatment centre assistant', root_path)

  =link_to('Your assistant dashboard', layouts_assistant_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmergencyAssistant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://file.myfontastic.com/594LEtWHkT8qvD2UeihGW4/icons.css" rel="stylesheet">

</head>
<body>
<%= render( :partial => 'layouts/header') %>
<%= yield %>

</body>
</html>

app/views/layouts/assistant.html.haml
%section.intro
  %h1 Your assistant dashboard
  %br
  %a{:href => '/'}Learn more about being an assistant
%section.links
  .link
    = link_to "Add a new centre", new_centre_path, :class => 'button'
  .link
    = link_to "Your centres", "", :class => 'button'

app/views/messages/index.html.haml
%section.intro
  %h1
    Become an assistant
  %p
    Help make a difference to health and treamtent centres by relaying information between the beople on the ground and the site.
  %br
  %p
    It's easy, simply respond to a request, sign up then start recording information. No pressure, if you are away from your phone the message will be redirected to another assistant within 15 minutes.


%section.messages
  %h2 New requests for assistants
  .inner
    .message
      %h3 +02 778928812
      %p Hi, I'm Terrance in Sierra Leone we have set up a new Ebola treatment centre and need many more doctors, nurses etc.
      %br
      %br
      %a{:href => '', :class => 'button'}
        Respond to this message
      %br
      %br
    .message
      %h3 +44 7531 7294 53
      %p My name's Irene, we need food and clothing. @ border in Hungary.
      %br
      %br
      %a{:href => '', :class => 'button'}
        Respond to this message
      %br
      %br

app/views/twilio/index.html.haml
=@message
=@from